# Generated by Django 5.1.3 on 2024-11-13 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id_customer', models.AutoField(primary_key=True, serialize=False)),
                ('identification', models.CharField(max_length=100, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True, default=None, null=True)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'db_table': 'tbl_customers',
                'indexes': [models.Index(fields=['identification'], name='tbl_custome_identif_d925b0_idx')],
                'constraints': [models.UniqueConstraint(fields=('first_name', 'last_name'), name='unique_customer_name')],
            },
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id_pet', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('weight', models.FloatField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.customer')),
            ],
            options={
                'verbose_name': 'Pet',
                'verbose_name_plural': 'Pets',
                'db_table': 'tbl_pets',
                'indexes': [models.Index(fields=['name'], name='tbl_pets_name_76ae19_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('age__gt', 0)), name='age_gt_zero'), models.CheckConstraint(condition=models.Q(('weight__gt', 0)), name='weight_gt_zero')],
            },
        ),
    ]
